version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/queue:cached
    env_file: .env
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

volumes:
  postgres-data:
